version: '3.7'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: arnotify
      MYSQL_USER: arnotify_user
      MYSQL_PASSWORD: arnotify_password
      MYSQL_ROOT_PASSWORD: arnotify_root_password
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    restart: always
    environment:
      PMA_PORT: 3306
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: arnotify_root_password
    ports:
      - 4000:80
    depends_on: 
      - db

volumes:
  mysql:

