version: '3.7'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - arnotify-db:/var/lib/mysql
      - ./data/mysql:/var/lib/mysql

volumes:
  arnotify-db:

