version: '3.7'
services:
  db:
    image: mariadb:10.9
    restart: always
    environment:
      MARIADB_DATABASE: arnotify
      MARIADB_USER: arnotify_user
      MARIADB_PASSWORD: arnotify_password
      MARIADB_ROOT_PASSWORD: arnotify_root_password
    ports:
      - '3306:3306'
    volumes:
      - mariadb:/var/lib/mariadb
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    restart: always
    environment:
      PMA_PORT: 3306
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: arnotify_root_password
    ports:
      - 4000:80
    depends_on:
      - db

volumes:
  mariadb:

